apiVersion: storage.k8s.io/v1
kind: StorageClass  
metadata:  
  name: demo-sts-sc  
  annotations:  
    storageclass.kubernetes.io/is-default-class: "true"  
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/vsan:52a74dd669c5ca33-50d47771366d91af/"
